/* ===========================================================================
   media.js — EVERY PICTURE SLOT IN THIS CASE STUDY, GROUPED BY SLIDE.

   Rebuilt 6 October to the new slide-structure sheet. This file is also the
   MAP: read down it and you see, slide by slide, how many pictures each one
   takes and what each is waiting for.

   ---------------------------------------------------------------------------
   HOW A SLOT IS NAMED
   ---------------------------------------------------------------------------
       slide-06_img-01
       |        |
       |        which picture on that slide - 01 is the first
       the slide it sits on, numbered as your deck is

   One slot is not a drawing at all: slide 27 holds the running prototype,
   so it is slide-27_prototype-01.

   ---------------------------------------------------------------------------
   TO ADD A DRAWING, YOU DO NOT EDIT THIS FILE
   ---------------------------------------------------------------------------
       the empty box on the page says   slide-06_img-01
       you export and save              assets/slide-06_img-01.png
       that is all

   PNG or JPG. The page asks the drawing itself how wide and how tall it is,
   so there is no shape to measure or type in either.

   `note` is what the EMPTY BOX SAYS while it is waiting. With names this
   numeric, that line is the only thing on screen telling you what a slot is
   for, so it earns its place. The CAPTION a reader reads is in copy.js.

   ---------------------------------------------------------------------------
   IF A DRAWING HAS TO KEEP A DIFFERENT FILE NAME
   ---------------------------------------------------------------------------
       'slide-06_img-01': { kind: 'image', src: 'assets/whatever.png' }

   Other kinds, for anything that is not a still drawing:
       video     { kind:'video',  src:'…mp4|gif', poster:'…', loop:true }
       figma     { kind:'figma',  src:'<figma share link OR embed url>' }
       local     { kind:'local',  src:'../../prototypes/<study>/x/index.html' }
       external  { kind:'external', src:'https://…' }

   ---------------------------------------------------------------------------
   TO CHECK YOUR OWN WORK
   ---------------------------------------------------------------------------
       CS.slideMap()              the whole structure, in the console
       CS.PrototypeEmbed.empty()  every slot still showing an empty box
   =========================================================================== */
window.CS = window.CS || {};

CS.MEDIA = {

  /* --- slide 01 · Title ------------------------------------------- */
  'slide-01_img-01': { note: 'The man sitting at the computer, beside the title.' },
  'slide-01_img-02': { note: 'Long horizontal band, roughly 16:1, along the bottom of the title slide.' },

  /* --- slide 02 · The business problem ----------------------------
     The band at the top of this slide is HALF picture and half door. Only
     the small square is a drawing; the wide half beside it is a surface
     with words on it that opens the page's one drawer, so it has no slot
     and nothing to draw. Its words are in copy.js, under slide-02. */
  'slide-02_img-01': { note: 'The small square at the top left of the band.' },

  /* --- slide 03 · Which stakeholders were effected -----------------
     Three people, stepped through with the click areas either side. Each one
     has TWO drawings: their portrait, and the square diagram at the foot of
     the panel beside them. */
  'slide-03_img-01': { note: 'User 1 \u00b7 the credit analyst.' },
  'slide-03_img-02': { note: 'User 2 \u00b7 the executive director.' },
  'slide-03_img-03': { note: 'User 3 \u00b7 the subject matter expert.' },

  /* The diagram at the foot of each person's panel. These are named after
     WHAT THEY ARE rather than by number, because there is more than one kind
     of picture on this slide now and "img-04" did not say which. The number
     in the middle is the person's place in the carousel, which is the order
     `personas` lists them in content.js. SQUARE. */
  'slide-03_user-1_collaboration-model': { note: 'User 1 \u00b7 the credit analyst\u2019s collaboration model. Square.' },
  'slide-03_user-2_collaboration-model': { note: 'User 2 \u00b7 the executive director\u2019s collaboration model. Square.' },
  'slide-03_user-3_collaboration-model': { note: 'User 3 \u00b7 the subject matter expert\u2019s collaboration model. Square.' },

  /* slides 04, 05 are words only */

  /* --- slide 06 · How I adjusted my approach ----------------------
     Seven diagrams in one run, stepped through with the click areas either
     side. The question above each one is in copy.js, under `questions`. */
  'slide-06_img-01': { note: 'What I found, diagram 1 of 7.' },
  'slide-06_img-02': { note: 'What I found, diagram 2 of 7.' },
  'slide-06_img-03': { note: 'What I found, diagram 3 of 7.' },
  'slide-06_img-04': { note: 'What I found, diagram 4 of 7.' },
  'slide-06_img-05': { note: 'What I found, diagram 5 of 7.' },
  'slide-06_img-06': { note: 'What I found, diagram 6 of 7.' },
  'slide-06_img-07': { note: 'What I found, diagram 7 of 7.' },

  /* slide 07 is words only */

  /* --- slide 08 · How I approached the solution ------------------- */
  'slide-08_img-01': { note: 'The diagram of how you approached the solution.' },

  /* slide 09 is a strip of words */

  /* --- slides 10 to 14 · Initial ideas, five diagrams ------------- */
  'slide-10_img-01': { note: 'Initial ideas, diagram 1 of 5.' },
  'slide-11_img-01': { note: 'Initial ideas, diagram 2 of 5.' },
  'slide-12_img-01': { note: 'Initial ideas, diagram 3 of 5.' },
  'slide-13_img-01': { note: 'Initial ideas, diagram 4 of 5.' },
  'slide-14_img-01': { note: 'Initial ideas, diagram 5 of 5.' },

  /* slides 15, 16 are words only */

  /* --- slides 17 to 20 · What didn't work, four diagrams ---------- */
  'slide-17_img-01': { note: 'What didn’t work, diagram 1 of 4.' },
  'slide-18_img-01': { note: 'What didn’t work, diagram 2 of 4.' },
  'slide-19_img-01': { note: 'What didn’t work, diagram 3 of 4.' },
  'slide-20_img-01': { note: 'What didn’t work, diagram 4 of 4.' },

  /* slides 21, 22 are words only */

  /* --- slides 23 to 26 · What we built, four diagrams ------------- */
  'slide-23_img-01': { note: 'What we built, diagram 1 of 4.' },
  'slide-24_img-01': { note: 'What we built, diagram 2 of 4.' },
  'slide-25_img-01': { note: 'What we built, diagram 3 of 4.' },
  'slide-26_img-01': { note: 'What we built, diagram 4 of 4.' },

  /* --- slide 27 · The prototype -----------------------------------
     Not a drawing: a whole page loaded inside the slide. `kind: 'local'`
     means it lives in this repository rather than out on the web. Point
     `src` at a different prototype and this slide follows. */
  'slide-27_prototype-01': {
    kind: 'local',
    src: '../../prototypes/industry-dashboard/final-kids-page/index.html',
    ratio: '16 / 9',
    renderWidth: 1600,   /* the width this dashboard was drawn for */
    startLabel: 'Run the prototype',
    note: 'The shipped dashboard, running.' },

  /* slides 28, 29 are words only */

  /* --- slide 30 · Back to case studies ---------------------------- */
  'slide-30_img-01': {
    note: 'The wide band at the very end. Long and low, roughly 16:4.' },

  /* =====================================================================
     THE ONE DRAWER - opened by the golden panel on slide 2
     =================================================================== */
  'drawer-01_img-01': { note: 'How the scope widened, in four steps.' }
};


