/* ===========================================================================
   media.js — EVERY PICTURE SLOT ON THIS PAGE, GROUPED BY SLIDE.

   A slot is named after where it sits:

       slide-03_img-01
       |        |
       |        which picture on that slide - 01 is the first
       the slide it sits on

   To add a drawing you do NOT edit this file. Save it in this page's assets
   folder under the slot's own name and it appears:

       the empty box says   slide-03_img-01
       you save             assets/slide-03_img-01.png

   `note` is what the empty box says while it waits - with names this
   numeric, it is the only thing on screen telling you what to draw. The
   CAPTION a reader reads is in copy.js, under `captions`, filed under the
   same slot name.

   `node tools/slide-map.js analyst-primer`, or CS.slideMap() in the browser
   console, prints the whole structure.
   =========================================================================== */
window.CS = window.CS || {};

CS.MEDIA = {

  /* --- slide 02 · Who they are ------------------------------------ */
  'slide-02_img-01': { note: 'Who we mean by an analyst.' },

  /* --- slide 03 · The working day --------------------------------- */
  'slide-03_img-01': { note: 'The analyst’s day drawn as one strip.' },

  /* --- slide 05 · The pile ---------------------------------------- */
  'slide-05_img-01': { note: 'The sources an analyst works from, all at once.' },

  /* --- slide 07 · What good looks like ---------------------------- */
  'slide-07_img-01': { note: 'What a better day would look like.' },

  /* --- slide 08 · Where to next ----------------------------------- */
  'slide-08_img-01': { note: 'Which case study went after which part of the day.' },

  /* --- slide 09 · Back to the worlds ------------------------------ */
  'slide-09_img-01': {
    note: 'The wide band at the very end. Long and low, roughly 16:4.' }
};


