/* ===========================================================================
   media.js — EVERY PICTURE SLOT IN THIS CASE STUDY, GROUPED BY SLIDE.

   A slot is named after where it sits: slide-03_img-01 is the first picture
   on slide 3. To add a drawing you do NOT edit this file - save it in this
   study's assets folder under the slot's own name and it appears.

   `note` is what the empty box says while it waits. The CAPTION a reader
   reads is in copy.js, under `captions`, filed under the same slot name.
   =========================================================================== */
window.CS = window.CS || {};

CS.MEDIA = {
  /* --- slide 03 · Back to the worlds ------------------------------ */
  'slide-03_img-01': {
    note: 'The wide band at the very end: the drawing that means “back to the worlds”. Long and low, roughly 16:4.' }
};


